apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deployer-data-pvc
  namespace: deployer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
