name: Go Backend Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🛠 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: 📦 Install dependencies
        run: go mod tidy

      - name: 🧪 Run unit tests
        run: go test ./... -v
